---
repos:
  - repo: https://github.com/razekmh/.github
    rev: v0.0.2
    hooks:
      - id: general-hooks
      - id: lua-hooks

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty check --ignore=unresolved-import
        language: python
        files: \.py$
