[project]
dependencies = [
    "fastapi>=0.127.0",
    "pydantic-settings>=2.12.0",
    "python-multipart>=0.0.21",
    "uvicorn>=0.40.0",
]
description = "Add your description here"
name = "mini-rag"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
